---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.conix.one
spec:
  tls:
    - hosts:
      - {{ domain }}
      secretName: tls
  ingressClassName: nginx
  rules:
    - host: {{ domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
