---
apiVersion: v1
kind: Service
metadata:
  name: {{ service }}
spec:
  selector:
    service: {{ service }}
  ports:
    - port: {{ port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ service }}
  labels:
    service: {{ service }}
spec:
  selector:
    matchLabels:
      service: {{ service }}
  replicas: 1
  template:
    metadata:
      labels:
        service: {{ service }}
    spec:
      containers:
      - name: {{ service }}
        image: {{ tag }}
        ports:
        - containerPort: {{ port }}
      imagePullSecrets:
      - name: regcred
